services:
  
  # mysql:
  #   image: mysql:8.0
  #   ports:
  #     - "1488:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=MySup3rP4ssw0rd!
  #     - MYSQL_DATABASE=BTBDatabase

  web: 
    container_name: Frontend 
    image: lanero/btb:frontend
    ports:
      - "5173:80"

  api:
    container_name: Backend 
    image: lanero/btb:backend
    ports:
      - "5211:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Ten cuidado con poner \" , puede causar errores 
      - ConnectionString=server=mysql;Port=3306;uid=root;pwd=MySup3rP4ssw0rd!;database=BTBDatabase;
    # volumes:
    #   - ./logs:/logs
    # depends_on:
    #   - mysql

    
    # volumes:
    #   # - bbddScripts:/var/lib/mysql
    #   - ./BBDD:/docker-entrypoint-initdb.d/
    

# volumes:
#   bbddScripts:
